# Generated by Django 5.1.3 on 2024-11-28 03:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultas',
            old_name='data_e_hora_consulta',
            new_name='data_hora',
        ),
        migrations.RemoveField(
            model_name='consultas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='user_id',
        ),
        migrations.AddField(
            model_name='consultas',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='API.pacientes'),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
