# Generated by Django 5.1.3 on 2024-11-12 23:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('data_e_hora_consulta', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('historico_medico', models.TextField()),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.AddField(
            model_name='consultas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pacientes'),
        ),
    ]
