# Generated by Django 5.1.3 on 2024-12-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='API.medico'),
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
