# Generated by Django 5.1.3 on 2024-12-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_consultas_medico_medico_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
