# Generated by Django 5.1.3 on 2024-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_consultas_pacientes_delete_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
