# Generated by Django 5.1.3 on 2024-12-10 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_pacientes_historico_medico_pacientes_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionarios',
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CPF'),
        ),
    ]
