# Generated by Django 5.1.3 on 2024-11-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_data_e_hora_consulta_consultas_data_hora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultas',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
