# Generated by Django 5.1.3 on 2024-12-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_delete_funcionarios_alter_pacientes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='historico_medico',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
