# Generated by Django 5.1.3 on 2024-12-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_funcionarios_alter_consultas_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='paciente',
            field=models.ForeignKey(default='Sem médico', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='API.pacientes'),
        ),
    ]
